#!/usr/bin/env bash
# install nginx in the web server
sudo apt update -y
sudo apt upgrade -y


sudo apt install nginx -y
sudo service nginx start


sudo chown -R "$USER":"$USER" /var/www/html
echo "Hello World!" > /var/www/html/index.nginx-debian.html