#!/usr/bin/env bash
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

echo "server {
  listen 80 default_server;
  listen [::]:80 default_server;

  root /var/www/html;

  index index.html index.htm index.nginx-debian.html;

  error_page 404 /404.html;

  server_name _;

  location / {
  add_header X-Served-By $HOSTNAME;
  try_files \$uri \$uri/ =404;
    }

    location /404 {
      root /var/www/html;
      internal;
    }

    location /redirect_me {
      return 301 https://youtu.be/dQw4w9WgXcQ;
    }
}" | sudo tee /etc/nginx/sites-available/default

sudo service nginx restart