#!/usr/bin/env bash
# installs haproxy and sets up a load balancer

# install haproxy
sudo apt update -y
sudo apt install haproxy -y

# set up load balancer
echo "frontend requests
  bind *:80
  default_backend servers

backend web-servers
  balance roundrobin
  	server 376420-web-01 52.23.177.244:80 check
  	server 376420-web-02 34.232.78.203:80 check" | sudo tee /etc/haproxy/haproxy.cfg

sudo service haproxy restart