#!/usr/bin/env bash
#creates the file /var/run/holbertonscript.pid containing its PID
echo $$ > /var/run/myscript.pid
#displays To infinity and beyond indefinitely
trap "echo I hate the kill command; rm /var/run/myscript.pid" SIGTERM
trap "echo Y U no love me?!" SIGINT
trap "rm /var/run/myscript.pid" SIGQUIT
while true
do
    echo "To infinity and beyond"
    sleep 2
done
