#!/usr/bin/env bash
# say hello to the world

i=1
while [ $i -le 10 ]; do
    echo "Hello";
    if [ $i -eq 4 ]
    then
        echo "bad luck";
    elif [ $i -eq 8 ]
    then
        echo "good luck";
    fi
    (("i++"));
done