#!/usr/bin/env bash
# check diff properties of file

file="school"
if [ -e "$file" ]
then
    echo "$file exists"
    if [ -s $file ]
    then
        echo "$file is not empty"
    else
        echo "$file is empty"
    fi
    if [ -f $file ]
    then
        echo "$file is a regular file"
    else
        echo "$file is not a regular file"
    fi
  else
    echo "$file does not exist"
fi