#!/usr/bin/env bash
# script that configures an Ubuntu server with Nginx
pkill apache2
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart